Web/BarakaBg.Web/Areas/Administration/Controllers/ProductsController.cs
namespace BarakaBg.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    using BarakaBg.Data.Common.Repositories;
    using BarakaBg.Data.Models;
    using BarakaBg.Services.Data;
    using BarakaBg.Services.Messaging;
    using BarakaBg.Web.ViewModels.Administration.Products;
    using BarakaBg.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    public class ProductsController : AdministrationController
    {
        private const string ProductsDirectoryPath = "\\images\\products\\";

        private readonly IDeletableEntityRepository<Product> productRepository;
        private readonly IProductsService productsService;
        private readonly ICategoriesService categoriesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;
        private readonly IEmailSender emailSender;

        private readonly string fullDirectoryPath;

        public ProductsController(
            IDeletableEntityRepository<Product> productRepository,
            IProductsService productsService,
            ICategoriesService categoriesService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment,
            IEmailSender emailSender)
        {
            this.productRepository = productRepository;
            this.productsService = productsService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
            this.environment = environment;
            this.emailSender = emailSender;

            this.fullDirectoryPath = this.environment.WebRootPath + ProductsDirectoryPath;
        }

        // GET: Administration/Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this.productRepository
                .AllWithDeleted()
                .Include(p => p.AddedByUser)
                .Include(p => p.Category);

            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var product = await this.productRepository
                .All()
                .Include(p => p.AddedByUser)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return this.NotFound();
            }

            return this.View(product);
        }

        public IActionResult Create()
        {
            var viewModel = new CreateProductInputModel
            {
                CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            // var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = await this.userManager.GetUserAsync(this.User);
            //try
            //{
            //    await this.productsService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            //}
            //catch (Exception e)
            //{
            //    this.ModelState.AddModelError(string.Empty, e.Message);
            //    input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
            //    return this.View(input);
            //}
            await this.productsService.CreateAsync<CreateProductInputModel>(input, input.UploadedImages, this.fullDirectoryPath, this.environment.WebRootPath);

            this.TempData["Message"] = "Product added successfully.";

            // return this.Json(input);
            return this.RedirectToAction(nameof(this.All), "Products", new { area = string.Empty });
        }

        // GET: Administration/Products/Edit/5
        public IActionResult Edit(int id)
        {
            var inputModel = this.productsService.GetById<EditProductInputModel>(id);
            inputModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
            return this.View(inputModel);
        }

        // POST: Administration/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditProductInputModel input)
        {
            if (id != input.Id)
            {
                return this.NotFound();
            }

            if (!this.ModelState.IsValid)
            {
                input.Id = id;
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            await this.productsService.UpdateAsync(id, input);

            return this.RedirectToAction(nameof(this.ById), new { area = string.Empty, id });
        }

        // GET: Administration/Products/Delete/5
        public async Task<IActionResult> SoftDelete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var product = await this.productRepository
                .All()
                .Include(p => p.AddedByUser)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return this.NotFound();
            }

            this.productRepository.Delete(product);

            await this.productRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.All), "Products", new { area = string.Empty });
        }

        // Administration/Products/Delete/5
        public async Task<IActionResult> HardDelete(int id)
        {
            var product = await this.productRepository
                .AllWithDeleted()
                .FirstOrDefaultAsync(x => x.Id == id);

            await this.productsService.DeleteAsync(id);

            await this.productRepository.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.All), "Products", new { area = string.Empty });
        }

        public async Task<IActionResult> Undelete(int id)
        {
            var undeleteResult = await this.productsService.UndeleteAsync(id);

            if (undeleteResult)
            {
                this.TempData["Alert"] = "Successfully restored product";
            }
            else
            {
                this.TempData["Error"] = "There was a problem restoring the product.";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var viewModel = new ProductsListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                ItemsCount = this.productsService.GetCount(),
                Products = this.productsService.GetAll<ProductInListViewModel>(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult Deleted()
        {
            var products = this.productsService.GetAllDeleted<DeletedProductViewModel>();
            return this.View(products);
        }

        public IActionResult ById(int id)
        {
            var product = this.productsService.GetById<SingleProductViewModel>(id);
            return this.View(product);
        }

        //[HttpPost]
        //public async Task<IActionResult> DeleteReview(string id, string returnUrl)
        //{
        //    var deleteResult = await this.productsService.DeleteReviewAsync(id);
        //    if (deleteResult)
        //    {
        //        this.TempData["Alert"] = "Successfully deleted review.";
        //    }
        //    else
        //    {
        //        this.TempData["Error"] = "There was a problem deleting the review.";
        //    }

        //    return this.LocalRedirect(returnUrl);
        //}
        [HttpPost]
        public async Task<IActionResult> SendToEmail(int id)
        {
            var product = this.productsService.GetById<ProductInListViewModel>(id);
            var html = new StringBuilder();
            html.AppendLine($"<h1>{product.Name}</h1>");
            html.AppendLine($"<h3>{product.CategoryName}</h3>");
            html.AppendLine($"<img src=\"{product.ImageUrl}\" />");
            await this.emailSender.SendEmailAsync("videnoff@students.softuni.bg", "BarakaBg", "videnoff@students.softuni.bg", product.Name, html.ToString());
            return this.RedirectToAction(nameof(this.ById), "Products", new { area = string.Empty, id });
        }

        private bool ProductExists(int id)
        {
            return this.productRepository.All().Any(e => e.Id == id);
        }
    }
}

Web/BarakaBg.Web/Controllers/ShoppingBagController.cs
namespace BarakaBg.Web.Controllers
{
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingBagController : BaseController
    {
        private readonly IShoppingBagService shoppingBagService;
        private readonly IProductsService productsService;

        private readonly string userId;
        private readonly bool isUserAuthenticated;
        private readonly ISession session;

        public ShoppingBagController(
            IShoppingBagService shoppingBagService,
            IProductsService productsService,
            IHttpContextAccessor contextAccessor)
        {
            this.shoppingBagService = shoppingBagService;
            this.productsService = productsService;

            this.userId = contextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            this.isUserAuthenticated = contextAccessor.HttpContext.User.Identity.IsAuthenticated;
            this.session = contextAccessor.HttpContext.Session;
        }

        public async Task<IActionResult> Index()
        {
            var shoppingBagProducts =
                await this.shoppingBagService
                    .GetAllProductsAsync<ShoppingBagProductViewModel>(
                        this.isUserAuthenticated,
                        this.session,
                        this.userId);

            if (shoppingBagProducts == null || !shoppingBagProducts.Any())
            {
                return this.RedirectToAction("Index", "Home");
            }

            return this.View(new ShoppingBagViewModel()
            {
                Products = shoppingBagProducts,
            });
        }

        [HttpGet("/ShoppingBag/Add/{productId:int}")]
        public async Task<IActionResult> Add(int productId)
        {
            var addResult =
                await this.shoppingBagService.AddProductAsync(this.isUserAuthenticated, this.session, this.userId, productId);

            if (addResult)
            {
                this.TempData["Alert"] = "Successfully added the product to the shopping cart.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem adding the product to the shopping cart.";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet("/ShoppingBag/Delete/{productId}")]
        public async Task<IActionResult> Delete(int productId)
        {
            var deleteResult = await this.shoppingBagService.DeleteProductAsync(this.isUserAuthenticated, this.session, this.userId, productId);

            if (deleteResult)
            {
                this.TempData["Alert"] = "Successfully removed the product from the shopping cart.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem removing the product from the shopping cart.";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet("/ShoppingBag/Quantity/{productId}")]
        public async Task<IActionResult> UpdateQuantity(int productId, bool increase)
        {
            var updateResult = await this.shoppingBagService.UpdateQuantityAsync(this.isUserAuthenticated, this.session, this.userId, productId, increase);

            if (updateResult)
            {
                this.TempData["Alert"] = "Successfully updated product quantity.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem updating the product quantity.";
            }

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/BarakaBg.Web/Controllers/WishListController.cs
namespace BarakaBg.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.WishList;
    using Microsoft.AspNetCore.Mvc;

    public class WishListController : BaseController
    {
        private readonly IWishListService wishListService;

        public WishListController(IWishListService wishListService)
        {
            this.wishListService = wishListService;
        }

        public IActionResult All()
        {
            var wishListProducts = this.wishListService
                .GetAll<WishListProductViewModel>(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            return this.View(wishListProducts);
        }

        public async Task<IActionResult> Add(int id)
        {
            var addResult = await this.wishListService.AddAsync(id, this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (addResult)
            {
                this.TempData["Alert"] = "Successfully added product to wishList.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem adding the product to wishList.";
            }

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deleteResult = await this.wishListService.DeleteAsync(id, this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (deleteResult)
            {
                this.TempData["Alert"] = "Successfully removed product from wishList.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem removing the product from wishList.";
            }

            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Web/BarakaBg.Web/Views/Products/All.cshtml
@using BarakaBg.Common
@using BarakaBg.Data.Models
@using Microsoft.AspNetCore.Identity
@model BarakaBg.Web.ViewModels.Products.ProductsListViewModel
@inject SignInManager<ApplicationUser> SignInManager

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-success alert-dismissible">@this.TempData["Message"]</div>
}

@{
    this.ViewData["Title"] = "All products";
}

<div class="form-group col-md">
    <form method="get">
        <div class="form-inline col-md">
            <input asp-for="SearchTerm" class="form-control col-md" placeholder="Search product..." />
            <div class="col col-form-label col-md">
                <button type="submit" class="btn btn-primary">
                    Search
                </button>
            </div>
        </div>
    </form>
</div>

<div class="container">
    <div class="row">
        @foreach (var product in Model.Products)
        {
            <div class="col-md-4 col-6">
                <div>
                    <a asp-action="ById" asp-route-id="@product.Id">
                        <img class="img-fluid" src="@product.ImageUrl" alt="@product.Name">
                    </a>
                    @if (this.SignInManager.IsSignedIn(this.User) && !this.User.IsInRole(GlobalConstants.AdministratorName))
                    {
                        <a asp-area="" asp-controller="WishList" asp-action="Add" asp-route-id="@product.Id" class="fav" data-placement="left" title="WishList">
                            <i class="fas fa-heart mr-0 pt-1"></i>
                        </a>
                        <a asp-area="" asp-controller="ShoppingBag" asp-action="Add" asp-route-productId="@product.Id" class="it-cart">
                            <span class="it-img">
                                <i class="fas fa-shopping-cart">
                                </i>
                            </span>
                            <span class="it-title">
                                Add To Cart
                            </span>
                        </a>
                    }
                </div>
                <div>
                    <div>
                        <h3>
                            <a asp-action="ById" asp-route-id="@product.Id" title="@product.Name">@product.Name</a>
                        </h3>
                        <div>
                            <h3 >
                                <span>
                                    Price:
                                </span>
                                <span>
                                    @product.Price lv.
                                </span>
                                </h3>
                        </div>
                    </div>
                    <div>
                        <a>
                            @product.Description.Substring(0, product.Description.Length > 200 ? 200 : product.Description.Length)
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<partial name="_PagingPartial" model="@Model" />

Web/BarakaBg.Web/Views/Products/ById.cshtml
@using BarakaBg.Common
@using BarakaBg.Web.ViewModels.Products
@using System.Globalization
@using System.Security.Claims
@model BarakaBg.Web.ViewModels.Products.SingleProductViewModel
@{
    this.ViewData["Title"] = Model.Name;
}

<title>
    @this.ViewData["Title"]
</title>

<!-- CSS -->


<div>
    @*<h2>
        @this.ViewData["Title"]
    </h2>*@
    <div class="row mb-4">
        <div class="pro-rating">
        </div>
        <div class="product-image">
            <a class="pro-img" href="@Model.ImageUrl">
                <img class="img-fluid w-100" src="@Model.ImageUrl" alt="@Model.Name">
            </a>
        </div>
        <div class="col-md-6 col-xl-6 product_details">
            <div class="product_details_info">
                <div class="product-title">
                    <h2>
                        @Model.Name
                    </h2>
                </div>
                <div class="product-inventory">
                    <h3>
                        <span>
                            Availability:
                        </span>
                        <span id="variant-inventory" class="in-stock">
                            @Model.Stock
                        </span>
                    </h3>
                </div>
                <div>
                    <h3>
                        <span>
                            Category:
                        </span>
                        <span>
                            @Model.CategoryName
                        </span>
                    </h3>
                </div>
                <div class="pro-price-label">
                    <div class="price-box" id="ProductPrice">
                        <h3>
                            <span>
                                Price:
                            </span>
                            <span>
                                @Model.Price lv
                            </span>
                            </h3>
                        @*<span class=money>
                            Price: @Model.Price lv
                        </span>*@
                    </div>

                    <a asp-area="" asp-controller="WishList" asp-action="Add" asp-route-id="@Model.Id" class="it-fav" data-toggle="tooltip" data-placement="top" title="WishList" style="margin-left: 379px;">
                        <i class="fas fa-heart mr-0 pt-1"></i>
                    </a>
                    <a asp-area="" asp-controller="ShoppingBag" asp-action="Add" asp-route-productId="@Model.Id" data-toggle="tooltip" data-placement="top" title="Add to Cart" style="margin-left: 67px;">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </div>
                <hr/>
                <div>
                    @Model.Description
                </div>
            </div>
            
            @*@{
                var ratingSum = ViewBag.RatingSum;
                var ratingCount = ViewBag.RatingCount;

                decimal rating = 0;

                if (ratingCount > 0)
                {
                    rating = (ratingSum / ratingCount);
                }

                var totalRating = decimal.Parse(rating.ToString());
            }*@

            @*<h2>@Model.Title</h2>*@

            @*<div>
                <span class="starFadeN" id="sRate1"></span>
                <span class="starFadeN" id="sRate2"></span>
                <span class="starFadeN" id="sRate3"></span>
                <span class="starFadeN" id="sRate4"></span>
                <span class="starFadeN" id="sRate5"></span>
            </div>*@

        </div>
        <div class="col col-md-6 col-xl-3" style="margin-left: 78px; margin-top: 82px; padding-right: 0px; padding-left: 0px; margin-right: 5px;">
            <h3>
                User Ratings:
            </h3>
            @foreach (var comment in Model.ProductComments)
            {
                <div class="row">
                    <div class="col-md-8">
                        @*<i>@comment.PublishedDate</i>*@
                        <br/>
                        @for (var i = 1; i <= comment.Rating; i++)
                        {
                            <span class="starGlowN"></span>
                        }
                        @for (var i = (comment.Rating + 1); i <= 5; i++)
                        {
                            <span class="starFadeN"></span>
                        }
                    </div>
                </div>

                <hr/>
            }
        </div>
            
        <hr />
        <partial name="_CommentBoxPartial"/>

    </div>

    <a asp-area="" asp-controller="Products" asp-action="All" class="btn btn-secondary">
        Back to All Products
    </a>

    @if (this.User.IsInRole(GlobalConstants.AdministratorName))
    {
        <a asp-area="Administration" asp-controller="Products" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary">
            Edit
        </a>

        <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#softDeleteModal">
            Soft delete
        </a>
        <div class="modal fade" id="softDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            Soft delete
                        </h5>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to soft delete this product?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            Close
                        </button>
                        <a asp-area="Administration" asp-controller="Products" asp-action="SoftDelete" asp-route-id="@this.Model.Id" class="btn btn-danger">
                            Soft delete
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#hardDeleteModal">
            Hard delete
        </a>
        <div class="modal fade" id="hardDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            Hard delete
                        </h5>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to hard delete this product?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            Close
                        </button>
                        <a asp-area="Administration" asp-controller="Products" asp-action="HardDelete" asp-route-id="@this.Model.Id" class="btn btn-danger">
                            Hard delete
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <a asp-area="Administration" asp-controller="Products" asp-action="Index" class="btn btn-secondary">
            Back to Products Administration
        </a>

        <li class="single-meta">
            <form method="post" asp-area="Administration" asp-controller="Products" asp-action="SendToEmail" asp-route-id="@Model.Id">
                <button class="btn btn-warning">
                    Send to my Email
                </button>
            </form>
        </li>
        <li class="single-meta">
            <button class="btn btn-warning" onclick="window.print();">
                Print
            </button>
        </li>
    }
</div>

@section Scripts {
    @*<script>
        function SCRate() {
            for (var i = 1; i <= @totalRating; i++) {
                $("#sRate" + i).attr('class', 'starGlowN');
            }
        }
        $(function(){
            SCRate();
        });
    </script>*@
}

<div class="modal" tabindex="-1" role="dialog" id="deleteModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <p>Do you want to delete "@Model.Name"?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="deleteForm.submit()">
                    Yes
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    No
                </button>
            </div>
        </div>
    </div>
</div>

<link href="~/css/site.css" rel="stylesheet" />