Web/BarakaBg.Web/Areas/Administration/Controllers/OrdersController.cs
namespace BarakaBg.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using BarakaBg.Data.Models.Enums;
    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : AdministrationController
    {
        private const int ItemsPerPage = 6;
        private const string AreaName = "Administration";
        private const string ControllerName = "Orders";

        private readonly IOrdersService ordersService;

        public OrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        [HttpGet("/Administration/Orders/Unprocessed/{pageNumber?}")]
        public IActionResult Unprocessed(int pageNumber = 1)
        {
            if (pageNumber <= 0)
            {
                return this.Unprocessed();
            }

            var processingAndUnprocessedOrders =
                this.ordersService.TakeProcessingAndUnprocessedOrders<OrderCheckViewModel>(pageNumber, ItemsPerPage);
            var unprocessedOrdersCount = this.ordersService.GetOrdersCountByCondition(OrderCondition.Unprocessed);
            var processingOrdersCount = this.ordersService.GetOrdersCountByCondition(OrderCondition.Processing);

            var viewModel = new OrderListViewModel
            {
                ItemsCount = unprocessedOrdersCount + processingOrdersCount,
                ItemsPerPage = ItemsPerPage,
                PageNumber = pageNumber,
                Orders = processingAndUnprocessedOrders,
                Area = AreaName,
                Controller = ControllerName,
                Action = nameof(this.Unprocessed),
            };

            return this.View(viewModel);
        }

        [HttpGet("/Administration/Orders/Processed/{pageNumber?}")]
        public IActionResult Processed(int pageNumber = 1)
        {
            if (pageNumber <= 0)
            {
                return this.Processed();
            }

            var processedOrders =
                this.ordersService.TakeOrdersByCondition<OrderCheckViewModel>(OrderCondition.Processed, pageNumber,
                    ItemsPerPage);
            var processedOrdersCount = this.ordersService.GetOrdersCountByCondition(OrderCondition.Processed);

            var viewModel = new OrderListViewModel
            {
                ItemsCount = processedOrdersCount,
                ItemsPerPage = ItemsPerPage,
                PageNumber = pageNumber,
                Orders = processedOrders,
                Area = AreaName,
                Controller = ControllerName,
                Action = nameof(this.Processed),
            };

            return this.View(viewModel);
        }

        [HttpGet("/Administration/Orders/Delivered/{pageNumber?}")]
        public IActionResult Delivered(int pageNumber = 1)
        {
            if (pageNumber <= 0)
            {
                return this.Delivered();
            }

            var deliveredOrders =
                this.ordersService.TakeOrdersByCondition<OrderCheckViewModel>(OrderCondition.Delivered, pageNumber,
                    ItemsPerPage);
            var deliveredOrdersCount = this.ordersService.GetOrdersCountByCondition(OrderCondition.Delivered);

            var viewModel = new OrderListViewModel
            {
                ItemsCount = deliveredOrdersCount,
                ItemsPerPage = ItemsPerPage,
                PageNumber = pageNumber,
                Orders = deliveredOrders,
                Area = AreaName,
                Controller = ControllerName,
                Action = nameof(this.Delivered),
            };

            return this.View(viewModel);
        }

        [HttpGet("/Administration/Orders/Deleted/{pageNumber?}")]
        public IActionResult Deleted(int pageNumber = 1)
        {
            if (pageNumber <= 0)
            {
                return this.Deleted();
            }

            var deletedOrders = this.ordersService.TakeDeletedOrders<OrderCheckViewModel>(pageNumber, ItemsPerPage);
            var deletedOrdersCount = this.ordersService.GetDeletedOrdersCount();

            var viewModel = new OrderListViewModel
            {
                ItemsCount = deletedOrdersCount,
                ItemsPerPage = ItemsPerPage,
                PageNumber = pageNumber,
                Orders = deletedOrders,
                Area = AreaName,
                Controller = ControllerName,
                Action = nameof(this.Deleted),
            };

            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            var order = this.ordersService.GetById<OrderInfoViewModel>(id);

            if (order == null)
            {
                this.TempData["Error"] = "Order not found.";
                return this.RedirectToAction(nameof(this.Unprocessed));
            }

            return this.View(order);
        }

        public async Task<IActionResult> SetStatus(string id, string status)
        {
            var actionResult = await this.ordersService.SetOrderStatusAsync(id, status);

            if (actionResult)
            {
                this.TempData["Alert"] = "Sucessfully changed order status.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem changing the order status.";
            }

            return this.RedirectToAction(status.ToString());
        }

        public async Task<IActionResult> Delete(string id)
        {
            var deleteResult = await this.ordersService.DeleteAsync(id);
            if (deleteResult)
            {
                this.TempData["Alert"] = "Successfully deleted order.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem deleting the order.";
            }

            return this.RedirectToAction(nameof(this.Unprocessed));
        }

        public async Task<IActionResult> Undelete(string id)
        {
            var undeleteResult = await this.ordersService.UndeleteAsync(id);
            if (undeleteResult)
            {
                this.TempData["Alert"] = "Successfully undeleted order.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem undeleting the order.";
            }

            return this.RedirectToAction(nameof(this.Deleted));
        }
    }
}

Web/BarakaBg.Web/Controllers/AddressesController.cs
namespace BarakaBg.Web.Controllers
{
    using System.Threading.Tasks;

    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Addresses;
    using Microsoft.AspNetCore.Mvc;

    public class AddressesController : BaseController
    {
        private readonly IAddressesService addressesService;

        public AddressesController(IAddressesService addressesService)
        {
            this.addressesService = addressesService;
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddressInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Create", "Orders");
            }

            var createResult = await this.addressesService.CreateAsync(model);

            if (createResult)
            {
                this.TempData["Alert"] = "Successfully added address.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem adding the address.";
            }

            return this.RedirectToAction("Create", "Orders");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var deleteResult = await this.addressesService.DeleteAsync(id);

            if (deleteResult)
            {
                this.TempData["Alert"] = "Successfully deleted address.";
            }
            else
            {
                this.TempData["Error"] = "There was a problem deleting the address.";
            }

            return this.RedirectToAction("Create", "Orders");
        }
    }
}

Web/BarakaBg.Web/Controllers/OrdersController.cs
namespace BarakaBg.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using BarakaBg.Data.Models;
    using BarakaBg.Data.Models.Enums;
    using BarakaBg.Services;
    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Addresses;
    using BarakaBg.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class OrdersController : BaseController
    {
        private const string ShoppingBagMessage = "The shopping cart is empty";

        private readonly IOrdersService ordersService;
        private readonly IAddressesService addressesService;
        private readonly ICountriesService countriesService;
        private readonly ITextService textService;
        private readonly IShoppingBagService shoppingBagService;

        private readonly string userId;

        public OrdersController(
            IShoppingBagService shoppingBagService,
            IHttpContextAccessor contextAccessor,
            IOrdersService ordersService,
            IAddressesService addressesService,
            ICountriesService countriesService)
        {
            this.shoppingBagService = shoppingBagService;
            this.ordersService = ordersService;
            this.addressesService = addressesService;
            this.countriesService = countriesService;

            this.userId = contextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
        }

        public async Task<IActionResult> Create()
        {
            var hasProduct = await this.shoppingBagService.AnyProductsAsync(this.userId);

            if (!hasProduct)
            {
                this.TempData["Error"] = ShoppingBagMessage;
                return this.RedirectToAction("Index", "Home");
            }

            var addresses = this.addressesService.GetAll<AddressViewModel>(this.userId);

            //foreach (var address in addresses)
            //{
            //    if (!string.IsNullOrEmpty(address.Description))
            //    {
            //        address.Description = this.textService.TruncateAtWord(address.Description, 30);
            //    }
            //}
            var countries = this.countriesService.GetAll();

            var email = this.User.Identity.Name;

            var model = new OrderCreateInputModel
            {
                Addresses = addresses,
                Email = email,
                Countries = countries,
            };

            await this.ordersService.CancelAnyProcessingOrders(this.userId);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderCreateInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var hasProducts = await this.shoppingBagService.AnyProductsAsync(this.userId);

                if (!hasProducts)
                {
                    this.TempData["Error"] = ShoppingBagMessage;
                    return this.RedirectToAction("Index", "Home");
                }

                var addresses = this.addressesService.GetAll<AddressViewModel>(this.userId);

                foreach (var address in addresses)
                {
                    address.Description = this.textService.TruncateAtWord(address.Description, 30);
                }

                var countries = this.countriesService.GetAll();

                var email = this.User.Identity.Name;

                input.Addresses = addresses;
                input.Email = email;
                input.Countries = countries;

                return this.View(input);
            }

            await this.ordersService.CreateAsync<OrderCreateInputModel>(input, this.userId);

            return this.RedirectToAction(nameof(this.Complete));
        }

        public async Task<IActionResult> Complete()
        {
            var hasProducts = await this.shoppingBagService.AnyProductsAsync(this.userId);
            if (!hasProducts)
            {
                this.TempData["Error"] = ShoppingBagMessage;
                return this.RedirectToAction("Index", "Home");
            }

            var orderId = await this.ordersService.CompleteOrderAsync(this.userId);

            if (this.ordersService.GetPayFormById(orderId) == PayForm.CashOnDelivery)
            {
                this.TempData["Alert"] = "Successfully registered order.";
            }

            var order = this.ordersService.GetById<OrderPayConditionViewModel>(orderId);

            return this.View(order);
        }

        [HttpGet("/Orders/History/{pageNumber?}")]
        public IActionResult History(int pageNumber = 1)
        {
            if (pageNumber <= 0)
            {
                return this.History();
            }

            var itemsPerPage = 6;
            var orders = this.ordersService.TakeOrdersByUserId<OrderCheckViewModel>(this.userId, pageNumber, itemsPerPage);
            var ordersCount = this.ordersService.GetOrdersCountByUserId(this.userId);

            var viewModel = new OrderListViewModel
            {
                ItemsCount = ordersCount,
                ItemsPerPage = itemsPerPage,
                PageNumber = pageNumber,
                Orders = orders,
            };

            return this.View(viewModel);
        }

        public IActionResult Details(string id)
        {
            if (!this.ordersService.UserHasOrder(this.userId, id))
            {
                this.TempData["Error"] = "Order not found.";
                return this.RedirectToAction("Index", "Home");
            }

            this.ViewData["OrderId"] = id;
            return this.View();
        }
    }
}

Web/BarakaBg.Web/ViewComponents/CartBodyViewComponent.cs
namespace BarakaBg.Web.ViewComponents
{
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using BarakaBg.Services;
    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Mvc;

    public class CartBodyViewComponent : ViewComponent
    {
        private readonly IShoppingBagService shoppingBagService;
        private readonly ITextService textService;

        public CartBodyViewComponent(IShoppingBagService shoppingBagService, ITextService textService)
        {
            this.shoppingBagService = shoppingBagService;
            this.textService = textService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = this.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var products = await this.shoppingBagService.GetAllProductsAsync<ShoppingBagProductViewModel>(this.User.Identity.IsAuthenticated, this.HttpContext.Session, userId);

            if (products != null)
            {
                foreach (var product in products)
                {
                    product.ProductName = this.textService.TruncateAtWord(product.ProductName, 15);
                }
            }

            var viewModel = new ShoppingBagViewModel
            {
                Products = products ?? new List<ShoppingBagProductViewModel>(),
            };

            return this.View(viewModel);
        }
    }
}

Web/BarakaBg.Web/ViewComponents/OrderDetailsViewComponent.cs
namespace BarakaBg.Web.ViewComponents
{
    using BarakaBg.Services;
    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Mvc;

    public class OrderDetailsViewComponent : ViewComponent
    {
        private readonly IOrdersService ordersService;
        private readonly ITextService textService;

        public OrderDetailsViewComponent(
            IOrdersService ordersService,
            ITextService textService)
        {
            this.ordersService = ordersService;
            this.textService = textService;
        }

        public IViewComponentResult Invoke(string orderId)
        {
            var order = this.ordersService.GetById<OrderViewModel>(orderId);

            foreach (var product in order.Products)
            {
                product.ProductName = this.textService.TruncateAtWord(product.ProductName, 30);
            }

            return this.View(order);
        }
    }
}

Web/BarakaBg.Web/ViewComponents/PaymentOrderViewComponent.cs
namespace BarakaBg.Web.ViewComponents
{
    using BarakaBg.Services.Data;
    using BarakaBg.Web.ViewModels.Payment;
    using Microsoft.AspNetCore.Mvc;

    public class PaymentOrderViewComponent : ViewComponent
    {
        private readonly IOrdersService ordersService;

        public PaymentOrderViewComponent(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        public IViewComponentResult Invoke(string orderId)
        {
            var payForm = this.ordersService.GetPayFormById(orderId);

            var viewModel = new PaymentViewModel
            {
                PayForm = payForm,
            };

            return this.View(viewModel);
        }
    }
}

Web/BarakaBg.Web/Views/Orders/Complete.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@model BarakaBg.Web.ViewModels.Orders.OrderPayConditionViewModel

@{
    this.ViewData["Title"] = "Complete Order";
}

<!-- Complete Order -->
<section class="checkout">
    <div class="container">
        <div class="row">
            <vc:order-details order-id="@Model.Id"></vc:order-details>
            @if (Model.PayCondition != BarakaBg.Data.Models.Enums.PayCondition.Paid)
            {
                <vc:payment-order order-id="@Model.Id"></vc:payment-order>
            }
        </div>
    </div>
</section>
<!-- End Complete Order -->

@section Scripts{
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe("@Configuration["Stripe:PublicKey"]");
        var antiForgeryToken = document.querySelector("#antiForgeryForm > input[type=hidden]").value;
        var checkoutButton = document.getElementById("checkout-button");
        checkoutButton.addEventListener("click", function () {
            fetch("/api/checkout", {
                method: "POST",
                headers: {
                    "X-CSRF-TOKEN": antiForgeryToken,
                }
            })
                .then(function (response) {
                    return response.json();
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({ sessionId: session.id });
                })
                .then(function (result) {
                    // If redirectToCheckout fails due to a browser or network
                    // error, you should display the localized error message to your
                    // customer using error.message.
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.error("Error:", error);
                });
        });
    </script>
}

Web/BarakaBg.Web/Views/Orders/Create.cshtml
@using System.Security.Claims
@using BarakaBg.Web.ViewModels.Addresses
@model BarakaBg.Web.ViewModels.Orders.OrderCreateInputModel

@{
    this.ViewData["Title"] = "Checkout";
}

<section class="checkout">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <form method="post" asp-controller="Orders" asp-action="Create" id="orderForm">
                    <h5>Billing Information</h5>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="UserFullName"></label>
                            <input asp-for="UserFullName" />
                            <span asp-validation-for="UserFullName" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Email"></label>
                            <input asp-for="Email" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="Phone"></label>
                            <input asp-for="Phone" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                    </div>
                    
                    <div class="form-group border-primary mb-0">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <label>
                                    <input asp-for="ShipmentType" type="radio" id="Home" value="Home" checked>
                                    <span class="font-weight-bold mr-2">
                                        To Home
                                    </span>
                                </label>
                                <label>
                                    <input asp-for="ShipmentType" type="radio" id="Office" value="Office">
                                    <span class="font-weight-bold">
                                        To Office
                                    </span>
                                </label>
                            </li>
                        </ul>
                        <span asp-validation-for="ShipmentType" class="text-danger"></span>
                    </div>
                    <hr />
                    <h4 class="mb-2">
                        Choose Address
                    </h4>
                    <div class="form-group border-primary mb-0">
                        <ul class="list-group">
                            @foreach (var address in Model.Addresses)
                            {
                                <li class="list-group-item">
                                    <label>
                                        <input asp-for="AddressId" type="radio" value="@address.Id" checked />
                                        @address.Street @address.CityName, @address.CityZIPCode,  @address.CityCountryName@(string.IsNullOrEmpty(address.Description) ? string.Empty : ", " + address.Description)
                                    </label>
                                    <div class="float-right">

                                        <a asp-area="" asp-controller="Addresses" asp-action="Delete" asp-route-id="@address.Id">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </div>
                                </li>
                            }
                        </ul>
                        <span asp-validation-for="AddressId" class="text-danger"></span>
                    </div>
                    <a class="btn btn-primary mt-2" data-toggle="collapse" href="#addressForm" role="button" aria-expanded="false" aria-controls="addressForm">
                        Add
                    </a>
                    <input asp-for="PayForm" hidden value="CashOnDelivery" />
                </form>
                <hr />
                <div class="collapse" id="addressForm">
                    <h4 class="mb-5">
                        Add Address
                    </h4>
                    <partial name="_AddAddressPartial" model="new AddressInputModel { UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier), Countries = Model.Countries }" />
                </div>
            </div>
            <div class="col-md-5">
                <div class="row">
                    <vc:cart-body-checkout></vc:cart-body-checkout>
                    <div class="col-md-12">
                        <div class="pay-meth">
                            <h5>
                                Payment Method
                            </h5>
                            <div class="pay-box">
                                <ul class="list-unstyled">
                                    <li>
                                        <input type="radio" name="payment" id="cashOnDeliveryInput" value="CashOnDelivery" checked />
                                        <label for="cashOnDeliveryInput"><span>
                                                <i class="fa fa-circle"></i>
                                            </span>
                                            Cash On Delivery</label>
                                    </li>
                                    <li>
                                        <input type="radio" name="payment" id="stripeInput" value="Stripe" />
                                        <label for="stripeInput"><span><i class="fa fa-circle"></i></span>
                                            Stripe</label>
                                    </li>
                                </ul>
                            </div>
                            <span asp-validation-for="PayForm" class="text-danger"></span>
                        </div>
                        <button type="button" name="button" class="ord-btn" id="orderButton">
                            Place Order
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Checkout -->

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#orderButton").click(function () {
                $("#orderForm").submit();
            });
            $("#cashOnDeliveryInput").click(function () {
                $("#PaymentType").val($(this).val());
            });
            $("#stripeInput").click(function () {
                $("#PaymentType").val($(this).val());
            });
        });
    </script>
}

Web/BarakaBg.Web/Views/Orders/Details.cshtml
@{
    this.ViewData["Title"] = "Order Details";
    var orderId = this.ViewData["OrderId"];
}

<!-- Order Details -->
<section class="checkout">
    <div class="container">
        <div class="row">
            <vc:order-details order-id="@orderId"></vc:order-details>
        </div>
    </div>
</section>

Web/BarakaBg.Web/Views/Orders/History.cshtml
@model BarakaBg.Web.ViewModels.Orders.OrderListViewModel

@{
    this.ViewData["Title"] = "Order History";
}